// <auto-generated />
using System;
using BusinessWorkflowEngine.Api.Workflows;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessWorkflowEngine.Api.Workflows.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20261001185110_AddWorkflowExecutionLease")]
    partial class AddWorkflowExecutionLease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.ApprovalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionComment")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("AssignedSubject", "Status", "CreatedAt");

                    b.ToTable("ApprovalTasks");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.ExecutionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId", "OccurredAt");

                    b.ToTable("ExecutionEvents");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeExecutionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<string>("NodeId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId", "OccurredAt");

                    b.ToTable("RuntimeExecutionEvents");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeHttpAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StepExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StepExecutionId")
                        .IsUnique();

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("RuntimeHttpActions");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeStepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId", "StartedAt");

                    b.ToTable("RuntimeStepExecutions");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("text");

                    b.Property<string>("CompletionJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StepExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StepExecutionId")
                        .IsUnique();

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("AssignedRole", "Status", "CreatedAt");

                    b.ToTable("RuntimeWorkItems");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeWorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentNodeId")
                        .HasColumnType("text");

                    b.Property<string>("DefinitionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefinitionRevision")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExecutionLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitiatorSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariablesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionName", "DefinitionRevision");

                    b.HasIndex("InitiatorSubject", "CreatedAt");

                    b.HasIndex("Status", "ExecutionLeaseUntil");

                    b.HasIndex("DefinitionName", "InitiatorSubject", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("RuntimeWorkflowInstances");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.WorkflowDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<decimal>("ApprovalThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("ApproverSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name", "Revision");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.WorkflowDefinitionRevision", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name", "Revision");

                    b.HasIndex("Name", "IsPublished");

                    b.ToTable("WorkflowDefinitionRevisions");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefinitionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefinitionRevision")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitiatorSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .HasColumnType("text");

                    b.Property<string>("RequesterReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InitiatorSubject", "CreatedAt");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.WorkflowIntegrationConnection", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("AuthHeaderName")
                        .HasColumnType("text");

                    b.Property<string>("AuthScheme")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtectedSecret")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("WorkflowIntegrationConnections");
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.ApprovalTask", b =>
                {
                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.WorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.ExecutionEvent", b =>
                {
                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.WorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeExecutionEvent", b =>
                {
                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.RuntimeWorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeHttpAction", b =>
                {
                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.RuntimeStepExecution", null)
                        .WithMany()
                        .HasForeignKey("StepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.RuntimeWorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeStepExecution", b =>
                {
                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.RuntimeWorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeWorkItem", b =>
                {
                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.RuntimeStepExecution", null)
                        .WithMany()
                        .HasForeignKey("StepExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.RuntimeWorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessWorkflowEngine.Api.Workflows.RuntimeWorkflowInstance", b =>
                {
                    b.HasOne("BusinessWorkflowEngine.Api.Workflows.WorkflowDefinitionRevision", null)
                        .WithMany()
                        .HasForeignKey("DefinitionName", "DefinitionRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
